In [9]:
import numpy as np
from numpy import random 
import pandas as pd

# Boolean arrays and masks

**Comparison Operators as ufuncs** #universal functions

In [ ]:
x  = np.array([1,2,3,4,5,])
#check comparison 
x > 3 #using any operator

array([False, False, False,  True,  True])

**Boolean Arrays**

In [11]:
y = random.randint(10, size=(2,2))
print (y)
y > 2

[[2 5]
 [6 1]]


array([[False,  True],
       [ True, False]])

**Counting number entries in the arrays eg True**


In [ ]:
y = random.randint(10, size=(2,2))
print (y)
print(np.count_nonzero(y > 2)) 

[[8 2]
 [6 8]]
3


In [ ]:
y = random.randint(10, size=(2,2))
print (y)
print(np.sum(y > 2, axis= 1)) #axis each row

[[4 1]
 [1 6]]
[1 1]


**Checking quick if values are true, can use any or all**


In [ ]:
y = random.randint(10, size=(2,2))
print (y)
print(np.any(y > 2, axis= 1))  #h

[[2 2]
 [4 6]]
[False  True]


In [20]:
y = random.randint(10, size=(2,2))
print (y)
print(np.all(y > 2, axis= 1)) 

[[0 3]
 [1 1]]
[False False]


**Boolen bitwise operators**

& - and 
| or a
~ used with  and (& ) or (|) meaning not
^ neither 

In [29]:
y = random.randint(10, size=(5,7))
print (y)
print("")
print(np.sum(( y < 2) & (y == 0) , axis= 1)) 

[[5 2 6 5 0 9 3]
 [0 0 4 5 9 9 2]
 [8 9 9 7 3 8 1]
 [3 0 2 5 6 1 1]
 [0 3 5 4 2 0 9]]

[1 2 0 1 2]


In [30]:
y = random.randint(10, size=(5,7))
print (y)
print("")
print(np.sum(( y < 2) | (y == 0) , axis= 1)) 

[[2 7 8 6 2 0 5]
 [2 7 7 7 2 5 3]
 [0 2 3 6 6 9 3]
 [9 8 9 9 3 4 7]
 [6 9 2 0 5 4 4]]

[1 0 1 0 1]


In [33]:
y = random.randint(10, size=(5,7))
print (y)
print("")
print(np.sum(~( y > 2) & (y == 0) , axis= 1)) 

[[4 8 5 8 5 1 7]
 [2 8 0 7 8 6 7]
 [6 6 9 5 0 2 9]
 [0 7 6 5 5 0 0]
 [8 6 2 2 2 2 3]]

[0 1 1 3 0]


In [34]:
y = random.randint(10, size=(5,7))
print (y)
print("")
print(np.sum(( y < 2) ^ (y == 0) , axis= 1)) 

[[2 4 4 5 8 6 2]
 [3 5 4 6 7 0 6]
 [8 0 2 4 1 7 1]
 [3 5 6 5 2 4 7]
 [6 3 1 6 4 6 8]]

[0 0 2 0 1]


**Masking**

- Means Indexing on selected values that have meet a certain condition 

In [24]:
y = random.randint(10, size=(5,7))
print (y)
print("")
y[y<5] #returns a MASKED 1D array of all the values in y that are less than 5.

[[7 5 1 8 7 7 0]
 [8 6 2 3 4 4 2]
 [1 2 8 7 0 0 5]
 [5 4 6 3 6 7 8]
 [4 3 5 3 5 3 1]]



array([1, 0, 2, 3, 4, 4, 2, 1, 2, 0, 0, 4, 3, 4, 3, 3, 3, 1], dtype=int32)

## Structured Arrays

- Makes it easy to refer to values either by name or index

In [7]:
#sample data

name = ["alice", "bob", "charlie", "dave", "eve"]
age = [25, 30, 35, 40, 45]
weight = [150, 160, 170, 180, 190]

In [12]:
#compound data type

data =np.zeros(5, dtype={"names":("name", "age", "weight"),
                          "formats": ("U10", "i4", "f8")})
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

- U10 means max length 10 

- i4 means 4 byres (32 bit ) Integer

- f8 means 4 byres (64 bit ) float

In [26]:
#POPULATING THE COMPOUND DATA TYPE

data["name"] = name
data["age"] = age   
data["weight"] = weight
data

array([('alice', 25, 150.), ('bob', 30, 160.), ('charlie', 35, 170.),
       ('dave', 40, 180.), ('eve', 45, 190.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [27]:
data["name"]

array(['alice', 'bob', 'charlie', 'dave', 'eve'], dtype='<U10')

In [33]:
older = data[data["age"] > 30]   #prints the rows of data where the age is greater than 30
print(older)

[('charlie', 35, 170.) ('dave', 40, 180.) ('eve', 45, 190.)]


In [32]:
bob_only = data[data ["name"] == "bob"] #printing the row of data where the name is "bob"
print (bob_only)

[('bob', 30, 160.)]
