## Imports go here:

In [4]:
import numpy as np

## Example of 1D Array

In [3]:
airline_accidents =[1,0,0]
airline_accidents_array = np.array(airline_accidents)
airline_accidents_array

array([1, 0, 0])

In [4]:
type(airline_accidents_array)

numpy.ndarray

In [5]:
airline_accidents_array.shape

(3,)

## Example of 2D Array

In [16]:
vote_party = [[0,9,1], [12,6,2]]
vote_party_array = np.array(vote_party)
vote_party_array

array([[ 0,  9,  1],
       [12,  6,  2]])

In [13]:
list_test = [[2], ["a"]]
list_test

[[2], ['a']]


**What is the difference between a Python List and a Numpy Array**

- Python lists can contain many different data types
python_list = ["santa", False' 23, .978, [1, 5 ,12]]

- Numpy Arrays can only contain the same Data Type
    - They use less space in memory

In [15]:
vote_party = [[0,9,1], [12,6,"a"]] #converts the array to string
vote_party_array = np.array(vote_party)
vote_party_array

array([['0', '9', '1'],
       ['12', '6', 'a']], dtype='<U21')

**Create Arrays**


- Functions used to create 

        -np.zeros
        -np.random
        -np.arange

**Creating Arrays with the np.zeros() function**

In [18]:
np.zeros((6,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros((6,3), dtype= int) #changing data types

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.random()

TypeError: 'module' object is not callable